kernel:
  image: linuxkit/kernel:4.9.59
  cmdline: "console=tty0 console=ttyS0"
init:
  - linuxkit/init:42a92119e1ca10380e0d33e26c0cbcf85b9b3558
  - linuxkit/runc:817fdc592eac6cb7804fa1721a43a7f6e23fb50f
  - linuxkit/containerd:82be2bbb7cf83bab161ffe2a64624ba1107725ff
  - linuxkit/ca-certificates:af4880e78edc28743f7c5e262678c67c6add4c26

onboot:
  # On the RPi3 we need to manually modprobe the network device driver.
  - name: netdev
    image: linuxkit/modprobe:2d153653d1111877a8f53704ef85063a44182ade
    command: ["modprobe", "smsc95xx"]
  # Create a bridge and add eth0 to it
  - name: bridge
    image: linuxkit/ip:54971b6664cb7b52912e909a8f6a45e5a5c94506
    binds:
      - /usr/bin/setup-bridge.sh:/usr/bin/setup-bridge.sh
    command: ["/usr/bin/setup-bridge.sh"]

services:
  - name: getty
    image: linuxkit/getty:626ccc8e1766c40447f29a790d3a7cfff126f2a2
    env:
     - INSECURE=true
  - name: rngd
    image: linuxkit/rngd:842e5e8ece7934f0cab9fd0027b595ff3471e5b9

files:
  - path: /usr/bin/setup-bridge.sh
    source: setup-bridge.sh
    mode: "0755"
  # Make sure we record the LinuxKit config in the image
  - path: etc/linuxkit-config
    metadata: yaml
trust:
  org:
    - linuxkit
    - library
